env:
  global:
    - secure: "Xe1UwrpaMsXJq3KX3azgYQyWLbZh2OELkJCCYRcW5c6Ke2EpNay3HCySyTN3YHDL0HclCel9jTayZy5JaWea+BgRQ9FdqGDC42wIO+19lCk13q6a37ncJh/0wgd8cNrhJb0u8NGD7TUbl2KS4emNOF5QLWABc3/PAwJ1pt2ZF0/3p7nJXlLnSgKl8VOtFl6Faf9btI8/YI5bPH/5zt30CT+ka9iGVN+yjqa8d4sJFg3en5oFvyzWucyME1D90hwZSwsKYOpMmEhzleHpU9afvFLoCDpQciAMV5y/zw+UxWXGwZD2keHyJoCP9EZMJVsmdgwUGfGRLUZbkc3d2rXn5kLbZ1+Q7fN0MJevs4Y1lS8hgjITr96Pr66dVtgcs6V1sZGAtIHRz6e4tQKcYAbh4mjdSws0NrvFLpWKdtDU/QdEB0Lbd0jTDJnal067ahqLcCMWU4RkbS2P4iKJU+8UfJ+Oeq4yrc8MYRFAX6VpG82jPdC56Taudd9lpXnyhpmCAkQpb7Tx2kBstVMOh398QIZ/Wh/wVFur4XDLsu0xOxbUKska7o3i07IRtTYy8WrqKmXAT81/ndfZehYZ5baFdgc3uPQvGcCO3Tp7TMTzDGO6tuvwAWtYSoAziRmUu1eoC4zl0eD9k92PaNfMXCnVA4kVF0NYF2gmA19y5Utp7o0="
    - secure: "c6BF90GwpiXtJyDDjTs4rSwP/eDFwbCYuIziohjrClte2lk5Y5AbkSxVtQ/R7T6Bml6oMmmeKY+uoASpAwc97xOIVR4l31U6NAxzADE0/SgB2/8csWi3HS6BHV+TaZXRSRnoGcJ4YDyQzYF2x/pqXfXTi7I4kkcf3zAeIdYqnK6cvgIj3Cvt32QGEMfCbBGMrOw445WdYUTiP6GeeNQ1ryGRD4CZuwfnCyJ241rrM7f2aPTna9ut6EV0sbuCY/M1egYLZWZFHuUoh6LOxlrEjDmBS1ssYKs/W51SJA4ahuIWtv0Pw6P2E9boY3raX/kmurTn7G26gnvQsEkYNWeOIzOXTZXvxhjAOCQK20VZTT5eMYzzZgnSYsHF7BkhqPPLtfJbVTIBsPk7B9ef6C5lqpBd3rMzBIQbEEPoemI/QYMH2RDbROpRtGqwAQMiVTaX5XCa/tlyU25WH9Q95vy4Kjc1fe26n8al75Sdkf+mjmZP4m8sF8fgsAJnyaIy+2yA50bYMqEWiXzi8umJk8GIj9MZvDrdmhRNbnq0w0KHEJXB0iPv4Al9erTq9yLP3Rtrh9vrsVFsroNzlX75kO2B0mFVF1lgwweXuy7RVu+Lbhdyjw4/QrbIgnt7p8rYLCfdBOALIv+qK4LBFtWHTQ7NAzFS7hN16PEMmd3YHzfG9pQ="
language: python

python:
  - "2.7"

jobs:
  include:
    - stage: SendDeclaration
      if: branch = master
      env: DRYRUN=1
      script:
        - python send_declaration.py
