env:
  global:
    - secure: "Xe1UwrpaMsXJq3KX3azgYQyWLbZh2OELkJCCYRcW5c6Ke2EpNay3HCySyTN3YHDL0HclCel9jTayZy5JaWea+BgRQ9FdqGDC42wIO+19lCk13q6a37ncJh/0wgd8cNrhJb0u8NGD7TUbl2KS4emNOF5QLWABc3/PAwJ1pt2ZF0/3p7nJXlLnSgKl8VOtFl6Faf9btI8/YI5bPH/5zt30CT+ka9iGVN+yjqa8d4sJFg3en5oFvyzWucyME1D90hwZSwsKYOpMmEhzleHpU9afvFLoCDpQciAMV5y/zw+UxWXGwZD2keHyJoCP9EZMJVsmdgwUGfGRLUZbkc3d2rXn5kLbZ1+Q7fN0MJevs4Y1lS8hgjITr96Pr66dVtgcs6V1sZGAtIHRz6e4tQKcYAbh4mjdSws0NrvFLpWKdtDU/QdEB0Lbd0jTDJnal067ahqLcCMWU4RkbS2P4iKJU+8UfJ+Oeq4yrc8MYRFAX6VpG82jPdC56Taudd9lpXnyhpmCAkQpb7Tx2kBstVMOh398QIZ/Wh/wVFur4XDLsu0xOxbUKska7o3i07IRtTYy8WrqKmXAT81/ndfZehYZ5baFdgc3uPQvGcCO3Tp7TMTzDGO6tuvwAWtYSoAziRmUu1eoC4zl0eD9k92PaNfMXCnVA4kVF0NYF2gmA19y5Utp7o0="

language: python

python:
  - "2.7"

script:
  - python test.py
